# Generated by Django 2.2.2 on 2019-06-16 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=20)),
                ('realname', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100, null=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('regtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
