# Generated by Django 2.2.2 on 2019-06-16 14:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('generalName', models.CharField(max_length=100)),
                ('pinyin', models.CharField(max_length=100)),
                ('goodsName', models.CharField(max_length=100)),
                ('component', models.CharField(max_length=200)),
                ('character', models.CharField(max_length=300)),
                ('function', models.CharField(max_length=300)),
                ('specification', models.CharField(max_length=100)),
                ('usageAndDosage', models.CharField(max_length=1000)),
                ('adverseReaction', models.CharField(max_length=2000)),
                ('contraindication', models.CharField(max_length=1000)),
                ('attention', models.CharField(max_length=1000)),
                ('drugInteraction', models.CharField(max_length=1000)),
                ('storage', models.CharField(max_length=200)),
                ('packing', models.CharField(max_length=100)),
                ('termOfValidity', models.CharField(max_length=100)),
                ('approvalNumber', models.CharField(max_length=100)),
                ('enterpriseName', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=20)),
                ('realName', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('postalCode', models.CharField(max_length=10)),
                ('regtime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.IntegerField()),
                ('state', models.CharField(max_length=10)),
                ('payMode', models.CharField(max_length=20)),
                ('disMode', models.CharField(max_length=20)),
                ('delTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('recTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('accTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('medicineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.Medicine')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.User')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageUrl', models.CharField(max_length=60)),
                ('medicineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('medicineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.Medicine')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userModel.User')),
            ],
        ),
    ]
