# Generated by Django 2.2.2 on 2019-06-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.AddField(
            model_name='medicine',
            name='classfication',
            field=models.CharField(default='待分类', max_length=100),
            preserve_default=False,
        ),
    ]
